- name: setting up backend of application
  hosts: backend
  become: yes
  vars_prompt:
  - name: Backenduser
    prompt: enter the user name of the backend configuration
    private: no
  tasks:
  - name: disabling the default nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs 
    ansible.builtin.dnf:
      name: nodejs
      state: installed
  
  
  - name: adding user
    ansible.builtin.user: 
      name: "{{Backenduser}}"

  - name: creating directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: downloading the backend file
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip


# file aready exists in the remote server 
  - name: unzip backend code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip # by deafult checks in ansible server 
      dest: /app
      remote_src: yes # this checks the file in remote server

  - name: install  npm dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copy backend service
    ansible.builtin.copy:
      src: backend.service
      dest: /etc/systemd/system/backend.service
    



  



