- name: installation of database 
  hosts: db
  become: yes
  vars:
    login_host:  db.fortunechits.online
  tasks:
  - name: installing mysql-server 
    ansible.builtin.dnf:
     name: mysql-server
     state: latest
  - name: start sql server
    ansible.builtin.service:
      name: mysqld
      state: started 
      enabled: yes
  #check password already set up
  - name: check db connection
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: "{{login_host}}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output
  - name: print result of mysql connection
    ansible.builtin.debug:
      msg: "output: {{mysql_connection_output}}"